---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip
        - dnsutils
